-- ============================================================================
-- DOCUMENTS TABLE - Digital Garden Content System
-- Stores all written content (principles, essays, fragments, projects, etc.)
-- ============================================================================

-- ============================================================================
-- 1. CREATE TABLE
-- ============================================================================

CREATE TABLE documents (
  id TEXT PRIMARY KEY,  -- ULID, generated by application
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  content_type TEXT NOT NULL,  -- open text: principles, essays, fragments, projects, poetry, artwork, books, etc.
  visibility TEXT NOT NULL DEFAULT 'private'
    CHECK (visibility IN ('public', 'supporter', '1v1', 'private')),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  body_md TEXT,  -- markdown content
  summary TEXT,  -- optional excerpt/description
  "order" INTEGER,  -- for manual sorting within series (quoted: reserved word)
  metadata JSONB DEFAULT '{}',  -- type-specific fields (medium, author, repo_url, etc.)
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  published_at TIMESTAMPTZ  -- set when status becomes published
);

-- ============================================================================
-- 2. INDEXES
-- ============================================================================

-- Single column indexes
CREATE INDEX idx_documents_slug ON documents(slug);
CREATE INDEX idx_documents_content_type ON documents(content_type);
CREATE INDEX idx_documents_visibility ON documents(visibility);
CREATE INDEX idx_documents_status ON documents(status);
CREATE INDEX idx_documents_published_at ON documents(published_at DESC) WHERE published_at IS NOT NULL;

-- Composite indexes for common queries
CREATE INDEX idx_documents_type_status_visibility ON documents(content_type, status, visibility);
CREATE INDEX idx_documents_user_type ON documents(user_id, content_type);

-- ============================================================================
-- 3. CONSTRAINTS
-- ============================================================================

-- Slugs must be unique per user
ALTER TABLE documents
  ADD CONSTRAINT documents_user_slug_unique UNIQUE (user_id, slug);

-- ============================================================================
-- 4. ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

-- Users can only read their own documents
CREATE POLICY "Users can view own documents"
  ON documents FOR SELECT
  USING (user_id = auth.uid());

-- Users can only insert documents with their own user_id
CREATE POLICY "Users can create own documents"
  ON documents FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Users can only update their own documents
CREATE POLICY "Users can update own documents"
  ON documents FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can only delete their own documents
CREATE POLICY "Users can delete own documents"
  ON documents FOR DELETE
  USING (user_id = auth.uid());

-- ============================================================================
-- 5. UPDATED_AT TRIGGER
-- ============================================================================

-- Use existing trigger function if it exists, otherwise create it
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to documents table
CREATE TRIGGER update_documents_updated_at
  BEFORE UPDATE ON documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- DOCUMENTS TABLE COMPLETE
-- ============================================================================
